### ISSUE TITLE
Inline harvest mongodb dependency 

### ISSUE THREAD

**Issue by kristofsajdak** [agco-adm/harvest#10]
Since we are adding a lot of Mongodb specific features ( e.g. onChange oplog integration ) and don't have the bandwidth to implement other adapters with the same behaviour, inlining the harvest mongodb dependency will make things simpler to manage.

**Comment by ssebro** [comment]
https://github.com/agco-adm/harvest/commit/3a7713096382f9d1feeb0bb02b5c5f5760e7ef72
